tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "afl-fuzz"
brew "atool"
brew "autojump"
brew "bat"
brew "openjdk@11"
brew "bazel"
brew "binutils"
brew "boost"
brew "sqlite"
brew "python@3.9"
brew "glib"
brew "python@3.8"
brew "cdecl"
brew "cheat"
brew "clang-format"
brew "cli11"
brew "cling"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl"
brew "poppler"
brew "diff-pdf"
brew "gnu-tar"
brew "diffoscope"
brew "docker"
brew "dos2unix"
brew "espeak"
brew "exa"
brew "fd"
brew "findutils"
brew "fish"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gdb"
brew "ghc"
brew "git"
brew "git-delta"
brew "git-gui"
brew "glances"
brew "gnu-sed"
brew "nghttp2"
brew "unbound"
brew "go"
brew "gobject-introspection"
brew "pango"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hub"
brew "hugo"
brew "hyperfine"
brew "icdiff"
brew "ipython", link: false
brew "jd"
brew "jq"
brew "node"
brew "pandoc"
brew "jupyterlab", link: false
brew "keychain"
brew "kubernetes-cli"
brew "llvm"
brew "make"
brew "mas"
brew "mercurial"
brew "mosh"
brew "neovim"
brew "nginx"
brew "openjdk"
brew "parallel"
brew "pdfgrep"
brew "prometheus"
brew "pstree"
brew "pup"
brew "pv"
brew "pyenv"
brew "pypy"
brew "python-yq"
brew "ranger"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "semgrep"
brew "shellcheck"
brew "stow"
brew "subversion"
brew "tag"
brew "tldr"
brew "tmux"
brew "tokei"
brew "tor"
brew "torsocks"
brew "trash"
brew "tree"
brew "unar"
brew "watch"
brew "wget"
brew "wireshark", link: false
brew "xsv"
brew "youtube-dl"
cask "1password"
cask "adoptopenjdk8"
cask "alfred"
cask "anki"
cask "appcleaner"
cask "balenaetcher"
cask "bettertouchtool"
cask "bisq"
cask "bitcoin-core"
cask "brave-browser"
cask "calibre"
cask "cold-turkey-blocker"
cask "db-browser-for-sqlite"
cask "detexify"
cask "djview"
cask "dropbox"
cask "electrum"
cask "freedom"
cask "garmin-express"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "handbrake"
cask "hex-fiend"
cask "intellij-idea-ce"
cask "iterm2"
cask "karabiner-elements"
cask "keycue"
cask "lunar"
cask "mactex"
cask "macvim"
cask "meld"
cask "messenger"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "nomachine"
cask "obs"
cask "playonmac"
cask "r"
cask "rescuetime"
cask "rstudio"
cask "sage"
cask "sequel-pro"
cask "skim"
cask "skype"
cask "smartgit"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "swiftdefaultappsprefpane"
cask "the-unarchiver"
cask "toggl-track"
cask "tor-browser"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "wasabi-wallet"
cask "webex"
cask "wireshark"
cask "workflowy"
cask "xquartz"
cask "zoomus"
mas "Be Focused Pro", id: 961632517
mas "DaisyDisk", id: 411643860
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LiquidText", id: 922765270
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "OwlOCR", id: 1499181666
mas "Pages", id: 409201541
mas "PDFCombo", id: 1030461463
mas "PDFOutliner", id: 420874236
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
