---
- name: Add GitHub CLI apt repository
  become: true
  block:
    - name: Add GitHub CLI apt key
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: "0644"
    - name: Add GitHub CLI apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        filename: github-cli

- name: Install core apt packages
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - build-essential  # Install before installing VirtualBox Guest Additions.
      - curl
      - dkms
      - fd-find
      - fish
      - fzf
      - gh
      - git
      - git-delta
      - golang
      - htop
      - jq
      - "linux-headers-{{ ansible_kernel }}"
      - neovim
      - python3-psutil
      - ripgrep
      - stow
      - tmux
      - tree
      - wget
    state: present
    update_cache: true

- name: Blacklist pc speaker module
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe.d/nobeep.conf
    content: "blacklist pcspkr\n"
    mode: "0644"

- name: Unload pc speaker module
  become: true
  community.general.modprobe:
    name: pcspkr
    state: absent

- name: Disable GNOME audible bell
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/audible-bell
    value: "false"
