---
- name: Add Neovim unstable PPA
  become: true
  block:
    - name: Add Neovim PPA key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9DBB0BE9366964F134855E2255F96FCF8231B6DD
        dest: /usr/share/keyrings/neovim-ppa.asc
        mode: "0644"
    - name: Add Neovim PPA source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/neovim-ppa.asc] https://ppa.launchpadcontent.net/neovim-ppa/unstable/ubuntu {{ ansible_distribution_release }} main"
        filename: neovim-ppa

- name: Add GitHub CLI apt repository
  become: true
  block:
    - name: Add GitHub CLI apt key
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
        mode: "0644"
    - name: Add GitHub CLI apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
        filename: github-cli

- name: Install core apt packages
  become: true
  ansible.builtin.apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - autojump
      - bat
      - build-essential  # Install before installing VirtualBox Guest Additions.
      - clang-format
      - clangd
      - curl
      - dkms
      - fd-find
      - fish
      - fzf
      - gh
      - git
      - git-delta
      - golang
      - htop
      - jq
      - neovim
      - npm
      - pipx
      - python3-psutil
      - ripgrep
      - shellcheck
      - stow
      - tmux
      - tree
      - wget
      - yamllint
    state: present
    update_cache: true

- name: Install pyright via pipx
  community.general.pipx:
    name: pyright

- name: Install tree-sitter-cli via npm
  become: true
  community.general.npm:
    name: tree-sitter-cli
    global: true

- name: Blacklist pc speaker module
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe.d/nobeep.conf
    content: "blacklist pcspkr\n"
    mode: "0644"

- name: Unload pc speaker module
  become: true
  community.general.modprobe:
    name: pcspkr
    state: absent

- name: Disable GNOME audible bell
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/audible-bell
    value: "false"

- name: Install Claude Code
  ansible.builtin.shell:
    cmd: curl -fsSL https://claude.ai/install.sh | bash
    creates: "{{ ansible_facts['env'].HOME }}/.local/bin/claude"
