---
# TODO: I don't remember why I used this approach in 2 tasks instead of ansible.builtin.user.
- name: Add Fish to standard login shells
  become: true
  become_method: ansible.builtin.sudo
  # This worked in at least one run, but now I'm getting errors
  # about sudo requiring a password. Odd.
  #
  # Can be worked around with
  # ansible-playbook --ask-become-pass.
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/fish

- name: Set login shell to Fish
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.command: chsh -s /opt/homebrew/bin/fish nick
  when: ansible_facts['user_shell'] != "/opt/homebrew/bin/fish"
  changed_when: ansible_facts['user_shell'] == "/opt/homebrew/bin/fish"
