---
- name: Basic settings
  ansible.builtin.import_tasks: basic_settings.yml

# This helps with running on Retina display. Also helps to set fractional scaling in
# Settings > Display.
- name: Get OilsDev VM info
  ansible.builtin.command:
    cmd: VBoxManage showvminfo OilsDev --machinereadable
  register: oilsdev_info
  changed_when: false

- name: Set OilsDev VM vram to 128 MB
  ansible.builtin.command:
    cmd: VBoxManage modifyvm OilsDev --vram 128
  when: "'vram=128' not in oilsdev_info.stdout"

- name: Set OilsDev VM clipboard to bidirectional
  ansible.builtin.command:
    cmd: VBoxManage modifyvm OilsDev --clipboard-mode bidirectional
  when: "'clipboard=\"bidirectional\"' not in oilsdev_info.stdout"

- name: Set OilsDev VM memory to 8219 MB
  ansible.builtin.command:
    cmd: VBoxManage modifyvm OilsDev --memory 8219
  when: "'memory=8219' not in oilsdev_info.stdout"

- name: Set OilsDev VM CPUs to 4
  ansible.builtin.command:
    cmd: VBoxManage modifyvm OilsDev --cpus 4
  when: "'cpus=4' not in oilsdev_info.stdout"
