---
- name: Basic settings
  ansible.builtin.import_tasks: basic_settings.yml

- name: Config symlinks
  ansible.builtin.import_tasks: config.yml

- name: Utils
  ansible.builtin.import_tasks: utils.yml
