#!/usr/bin/env -S ansible-playbook --ask-become-pass

---
- name: Check working directory
  hosts: localhost
  connection: local
  tasks:
    - name: Check working directory
      ansible.builtin.debug:
        msg: Check we are running in the directory of the script.
      failed_when: not ansible_env.PWD.endswith('/.dotfiles/ansible')

- name: Show facts available on the system
  hosts: localhost
  connection: local
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts

- name: Apply role
  hosts: localhost
  connection: local
  roles:
    - role: nick_mac
      when: ansible_facts["os_family"] == "Darwin"
