---
- name: Stow config into ~/.config
  ansible.builtin.command:
    cmd: stow --restow --target={{ ansible_facts["env"]["XDG_CONFIG_HOME"] | default(ansible_facts["env"].HOME + "/.config") }} --dir={{ playbook_dir }}/.. config
