---
- name: Config symlinks
  ansible.builtin.import_tasks: config.yml

- name: Install lemonade
  ansible.builtin.command:
    cmd: go install github.com/lemonade-command/lemonade@latest
  environment:
    GOPATH: "{{ ansible_facts['env'].HOME }}/go"
